import type { Metadata } from "next";
import Header from "@/app/components/header";
import { RootProvider } from "@/app/hooks/RootContext";
import { geistSans, geistMono } from "@/app/fonts/fonts";
import "./ui/globals.css";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-[#111111]`}
      >
        <RootProvider>
          <Header />
          {children}
        </RootProvider>
      </body>
    </html>
  );
}
